# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stormpath Notes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stormpath Notes

  pod 'Stormpath', '~> 3.0'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'AWSDynamoDB', '~> 2.5'
  pod 'AWSS3', '~> 2.5'
  pod 'AWSLambda', '~> 2.5'
  pod 'AWSCognito', '~> 2.5'

end
